ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/imovel__c.object-meta.xml
<CustomObject>
    <description>Exibe informações sobre imóveis.</description>
    <label>Imóvel</label>
    <nameField>
        <displayFormat>IMO - {0000}</displayFormat>
        <label>Nome de Imóvel</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Imóveis</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Banheiro__c.field-meta.xml
<CustomField>
    <fullName>Banheiro__c</fullName>
    <inlineHelpText>Insira o número de banheiros.</inlineHelpText>
    <label>Banheiro</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Copa__c.field-meta.xml
<CustomField>
    <fullName>Copa__c</fullName>
    <inlineHelpText>Insira o número de copas.</inlineHelpText>
    <label>Copa</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Cozinha__c.field-meta.xml
<CustomField>
    <fullName>Cozinha__c</fullName>
    <inlineHelpText>Insira o número de cozinhas.</inlineHelpText>
    <label>Cozinha</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Garagem__c.field-meta.xml
<CustomField>
    <fullName>Garagem__c</fullName>
    <inlineHelpText>Insira o número de carros suportados pela garagem.</inlineHelpText>
    <label>Garagem</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Quartos__c.field-meta.xml
<CustomField>
    <fullName>Quartos__c</fullName>
    <inlineHelpText>Insira o número de quartos do imóvel.</inlineHelpText>
    <label>Quartos</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Sala__c.field-meta.xml
<CustomField>
    <fullName>Sala__c</fullName>
    <inlineHelpText>Insira o número de salas.</inlineHelpText>
    <label>Sala</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Suite__c.field-meta.xml
<CustomField>
    <fullName>Suite__c</fullName>
    <inlineHelpText>Insira o número de suítes.</inlineHelpText>
    <label>Suíte</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Tipo_do_Imovel__c.field-meta.xml
<CustomField>
    <fullName>Tipo_do_Imovel__c</fullName>
    <inlineHelpText>Escolha o tipo do imóvel</inlineHelpText>
    <label>Tipo do Imóvel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Casa</fullName>
            </value>
            <value>
                <fullName>Apartamento</fullName>
            </value>
            <value>
                <fullName>Chácara</fullName>
            </value>
            <value>
                <fullName>Kitnet</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/objects/imovel__c/fields/Valor__c.field-meta.xml
<CustomField>
    <fullName>Valor__c</fullName>
    <inlineHelpText>Insira o valor do imóvel.</inlineHelpText>
    <label>Valor</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Currency</type>
</CustomField>

ImobiliariaPadillaProject/force-app/main/default/classes/ImobiliariaController.cls
public with sharing class ImobiliariaController {
    
    public Integer quartos {get; set;}
    public Integer banheiros {get; set;}
    public Integer salas {get; set;}
    public Integer cozinhas {get; set;}
    public Integer copas {get; set;}
    public Integer suites {get; set;}
    public Integer vagas {get; set;}
    public Integer valor {get; set;}
    public String tipoImovel {get; set;}


    public List<SelectOption> getMinhasOpcoes(){

        Schema.DescribeFieldResult describeResult = Imovel__c.Tipo_do_Imovel__c.getDescribe();

        List<Schema.PicklistEntry> entries = describeResult.getPicklistValues();

        List<SelectOption> optionsReturn = new List<SelectOption>();

        for(Schema.PicklistEntry pEntry: entries){
            if(pEntry.isActive()){
                optionsReturn.add(new SelectOption(pEntry.getValue(), pEntry.getLabel()));
            }
        }

        return optionsReturn;

    }


    public void salvar(){
        Imovel__c objImovel = new Imovel__c();
        
        objImovel.Quartos__c = quartos;
        objImovel.Banheiro__c = quartos;
        objImovel.Sala__c = salas;
        objImovel.Cozinha__c = cozinhas;
        objImovel.Copa__c = copas;
        objImovel.Suite__c = suites;
        objImovel.Garagem__c = vagas;
        objImovel.Valor__c = valor;
        objImovel.Tipo_do_Imovel__c = tipoImovel;

        

        try {
            
            if(objImovel.Tipo_do_Imovel__c != 'Nenhum' && objImovel != null){            
                insert objImovel;

                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.CONFIRM, 'Imóvel cadastrado com sucesso!'));


                quartos = null;
                banheiros = null;
                salas = null;
                cozinhas = null;
                copas = null;
                suites = null;
                vagas = null;
                valor = null;
                tipoImovel = null;
            }
            else{
                Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'O campo tipo do imóvel deverá ser preenchido!'));
            }

        } catch (DmlException e) {
            Apexpages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'ERRO!'));
        }
    }

}